SET(SEVENZIP_SEARCH_ROOTS)

IF(SEVENZIP_ROOT)
	#SET(SEVENZIP_ROOT PATHS ${SEVENZIP_ROOT} NO_DEFAULT_PATH)
	LIST(APPEND SEVENZIP_SEARCH_ROOTS ${SEVENZIP_ROOT})
ELSE()
	LIST(APPEND SEVENZIP_SEARCH_ROOTS ${CMAKE_CURRENT_SOURCE_DIR}/../../../7zip)
ENDIF()

FOREACH(search ${SEVENZIP_SEARCH_ROOTS})
	if(EXISTS "${search}/CPP/7zip/MyVersion.h")
		SET(SEVENZIP_ROOT_DIR ${search})
		SET(SEVENZIP_INCLUDE_DIR ${search}/CPP)
	ENDIF()
ENDFOREACH()


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(7Zip REQUIRED_VARS SEVENZIP_INCLUDE_DIR)

IF(ZLIB_FOUND)
    SET(SEVENZIP_INCLUDE_DIR ${SEVENZIP_INCLUDE_DIR})
ENDIF()

