"""
CONFIG(release, debug|release) {
  QMAKE_CXXFLAGS += /Zi
  QMAKE_LFLAGS += /DEBUG
}
"""

import os

Import('qt_env')

env = qt_env.Clone()

env.EnableQtModules('Core')

env.AppendUnique(CPPPATH = [
    os.path.join('${SEVENZIPPATH}', 'CPP')
])

env.AppendUnique(CPPDEFINES = [
    '_UNICODE',
    '_WINDLL',
    'WIN32',
    'NOMINMAX'
])

env.AppendUnique(LIBS = [
    'kernel32',
    'user32',
    'oleaut32',
    'ole32'
])

cpp_files = [ x for x in Glob('*.cpp')  ]

lib = env.SharedLibrary('archive', cpp_files + env.RES('version.rc'))

# Not sure why this has to live in DLLs..
env.InstallModule(lib, subdir = 'DLLs')
